import Foundation

/// Bidirectional map between the visual muscle mesh's SceneKit node names and
/// the app's muscle vocabulary, loaded from `musclegroup_node_names.json`
/// (generated by `Tools/blender/export_muscle_obj.py` alongside `BodyMuscle.obj`).
///
/// Every exported muscle object becomes one addressable SceneKit child node.
/// This resolves a tapped node back to its `MuscleGroup` (and sub-head, when the
/// object belongs to one) and — the other direction — enumerates every node that
/// makes up a given candidate region so a highlight can be applied group-wide or
/// head-wide. Mirrors `BodyHitVolumes.load()`'s bundle-JSON pattern.
///
/// Joints and face zones carry no muscle geometry, so lookups for them return
/// `nil`/`[]` rather than failing — callers just skip drawing a muscle highlight.
nonisolated enum MuscleNodeNames {
    /// node name → owning `MuscleGroup` raw value.
    static var groupByNode: [String: String] { loaded.groupByNode }
    /// node name → owning sub-head name (absent when the object isn't part of a head).
    static var headByNode: [String: String] { loaded.headByNode }
    /// `MuscleGroup` raw value → its node names.
    static var nodesByGroup: [String: [String]] { loaded.nodesByGroup }
    /// sub-head name → its node names.
    static var nodesByHead: [String: [String]] { loaded.nodesByHead }

    /// The node names that should light up for a candidate `region`, which may be
    /// a `MuscleGroup` raw value OR a sub-head name. A head highlights only its
    /// own belly nodes; a group highlights all of its nodes. Joints / face zones
    /// have no muscle geometry and return `[]`.
    static func nodeNames(forRegion region: String) -> [String] {
        if let heads = nodesByHead[region] { return heads }
        if let group = nodesByGroup[region] { return group }
        return []
    }

    /// Which of the given candidate regions a tapped muscle node belongs to,
    /// preferring the finer sub-head over its parent group — mirroring the hit
    /// resolver's "smallest volume wins" rule so a tap on a triceps head selects
    /// the head candidate, not the whole-triceps candidate, when both are shown.
    static func matchingCandidate(forNode node: String, among candidates: Set<String>) -> String? {
        if let head = headByNode[node], candidates.contains(head) { return head }
        if let group = groupByNode[node], candidates.contains(group) { return group }
        return nil
    }

    // MARK: - Loading

    private struct Entry: Decodable {
        let group: String
        let head: String?
    }
    private struct FileShape: Decodable {
        let nodes: [String: Entry]
    }

    struct Maps {
        var groupByNode: [String: String] = [:]
        var headByNode: [String: String] = [:]
        var nodesByGroup: [String: [String]] = [:]
        var nodesByHead: [String: [String]] = [:]
    }

    private static let loaded: Maps = load()

    static func load(bundle: Bundle = .main) -> Maps {
        guard let url = bundle.url(forResource: "musclegroup_node_names", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let file = try? JSONDecoder().decode(FileShape.self, from: data)
        else { return Maps() }

        var maps = Maps()
        for (node, entry) in file.nodes {
            maps.groupByNode[node] = entry.group
            maps.nodesByGroup[entry.group, default: []].append(node)
            if let head = entry.head {
                maps.headByNode[node] = head
                maps.nodesByHead[head, default: []].append(node)
            }
        }
        return maps
    }
}
