import Foundation

/// Bidirectional map between the anatomy mesh's SceneKit node names and the app
/// vocabulary, loaded from `anatomy_node_names.json` (generated by
/// `Tools/blender/export_anatomy.py` alongside `BodyAnatomy.obj`). Each exported
/// object is one addressable node. Resolves a tapped node to its group / sub-head
/// / face zone / joint, and enumerates the nodes of a candidate region so a
/// highlight can light it. head-skin nodes carry only a layer (no region).
nonisolated enum MuscleNodeNames {
    static var groupByNode: [String: String] { loaded.groupByNode }
    static var headByNode: [String: String] { loaded.headByNode }
    static var faceZoneByNode: [String: String] { loaded.faceZoneByNode }
    static var jointByNode: [String: String] { loaded.jointByNode }
    static var layerByNode: [String: String] { loaded.layerByNode }
    static var nodesByGroup: [String: [String]] { loaded.nodesByGroup }
    static var nodesByHead: [String: [String]] { loaded.nodesByHead }
    static var nodesByFaceZone: [String: [String]] { loaded.nodesByFaceZone }
    static var nodesByJoint: [String: [String]] { loaded.nodesByJoint }

    /// Node names to light for a candidate region (group / head / face zone /
    /// joint). Finer-grained wins: head, then face zone, then joint, then group.
    static func nodeNames(forRegion region: String) -> [String] {
        if let h = nodesByHead[region] { return h }
        if let f = nodesByFaceZone[region] { return f }
        if let j = nodesByJoint[region] { return j }
        if let g = nodesByGroup[region] { return g }
        return []
    }

    /// Which candidate a tapped node belongs to, finest-first (head > faceZone >
    /// joint > group), so a tap resolves to the most specific offered region.
    static func matchingCandidate(forNode node: String, among candidates: Set<String>) -> String? {
        if let h = headByNode[node], candidates.contains(h) { return h }
        if let f = faceZoneByNode[node], candidates.contains(f) { return f }
        if let j = jointByNode[node], candidates.contains(j) { return j }
        if let g = groupByNode[node], candidates.contains(g) { return g }
        return nil
    }

    private struct Entry: Decodable {
        let layer: String
        let group: String?
        let head: String?
        let faceZone: String?
        let joint: String?
    }
    private struct FileShape: Decodable { let nodes: [String: Entry] }

    struct Maps {
        var groupByNode: [String: String] = [:]
        var headByNode: [String: String] = [:]
        var faceZoneByNode: [String: String] = [:]
        var jointByNode: [String: String] = [:]
        var layerByNode: [String: String] = [:]
        var nodesByGroup: [String: [String]] = [:]
        var nodesByHead: [String: [String]] = [:]
        var nodesByFaceZone: [String: [String]] = [:]
        var nodesByJoint: [String: [String]] = [:]
    }

    private static let loaded: Maps = load()

    static func load(bundle: Bundle = .main) -> Maps {
        guard let url = bundle.url(forResource: "anatomy_node_names", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let file = try? JSONDecoder().decode(FileShape.self, from: data)
        else { return Maps() }
        var m = Maps()
        for (node, e) in file.nodes {
            m.layerByNode[node] = e.layer
            if let g = e.group { m.groupByNode[node] = g; m.nodesByGroup[g, default: []].append(node) }
            if let h = e.head { m.headByNode[node] = h; m.nodesByHead[h, default: []].append(node) }
            if let f = e.faceZone { m.faceZoneByNode[node] = f; m.nodesByFaceZone[f, default: []].append(node) }
            if let j = e.joint { m.jointByNode[node] = j; m.nodesByJoint[j, default: []].append(node) }
        }
        return m
    }
}
